<a href="https://colab.research.google.com/github/Aashi779/DeepLearningwithPytorch/blob/main/PytorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
x = np.array([[1,2,4],[5,6,7],[9,7,8]])


In [4]:
x

array([[1, 2, 4],
       [5, 6, 7],
       [9, 7, 8]])

In [5]:
x.shape

(3, 3)

In [6]:
type(x)

numpy.ndarray

In [7]:
data = [[1,2,4],[5,6,7],[9,7,8]]
x_tensor = torch.tensor(data)

In [8]:
x_tensor

tensor([[1, 2, 4],
        [5, 6, 7],
        [9, 7, 8]])

In [9]:
x_tensor.shape

torch.Size([3, 3])

In [10]:
x_tensor.size()

torch.Size([3, 3])

In [11]:
scalar = torch.tensor(5)

In [12]:
scalar

tensor(5)

In [13]:
scalar.size()


torch.Size([])

In [14]:
scalar.item()

5

In [15]:
vector = torch.tensor([5, 9])

In [16]:
vector

tensor([5, 9])

In [17]:
vector.shape

torch.Size([2])

In [18]:
'''
scalar = single number
vector = 1D array
matrix = 2D array
tensor = ND array
'''

'\nscalar = single number \nvector = 1D array\nmatrix = 2D array\ntensor = ND array\n'

In [21]:
# Methods
zeros_tensor = torch.zeros(6)
zeros_tensor

tensor([0., 0., 0., 0., 0., 0.])

In [20]:
zeros_tensor = torch.zeros((5, 6)) # for ones as well

In [22]:
torch.rand(6)

tensor([0.0914, 0.6120, 0.6343, 0.7532, 0.7905, 0.9343])

In [23]:
torch.rand((4, 6))

tensor([[0.0979, 0.7402, 0.2232, 0.4109, 0.8403, 0.9009],
        [0.1808, 0.3867, 0.3371, 0.0513, 0.7556, 0.6949],
        [0.4462, 0.9483, 0.1042, 0.7896, 0.3867, 0.3052],
        [0.4522, 0.1181, 0.4525, 0.0826, 0.9709, 0.8861]])

In [24]:
x = torch.rand((4, 6))

In [25]:
x.shape

torch.Size([4, 6])

In [26]:
x.device # by default device is cpu

device(type='cpu')