<a href="https://colab.research.google.com/github/Aashi779/DeepLearningwithPytorch/blob/main/PytorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
x = np.array([[1,2,4],[5,6,7],[9,7,8]])


In [4]:
x

array([[1, 2, 4],
       [5, 6, 7],
       [9, 7, 8]])

In [5]:
x.shape

(3, 3)

In [6]:
type(x)

numpy.ndarray

In [7]:
data = [[1,2,4],[5,6,7],[9,7,8]]
x_tensor = torch.tensor(data)

In [8]:
x_tensor

tensor([[1, 2, 4],
        [5, 6, 7],
        [9, 7, 8]])

In [9]:
x_tensor.shape

torch.Size([3, 3])

In [10]:
x_tensor.size()

torch.Size([3, 3])

In [11]:
scalar = torch.tensor(5)

In [12]:
scalar

tensor(5)

In [13]:
scalar.size()


torch.Size([])

In [14]:
scalar.item()

5

In [15]:
vector = torch.tensor([5, 9])

In [16]:
vector

tensor([5, 9])

In [17]:
vector.shape

torch.Size([2])

In [18]:
'''
scalar = single number
vector = 1D array
matrix = 2D array
tensor = ND array
'''

'\nscalar = single number \nvector = 1D array\nmatrix = 2D array\ntensor = ND array\n'

In [21]:
# Methods
zeros_tensor = torch.zeros(6)
zeros_tensor

tensor([0., 0., 0., 0., 0., 0.])

In [20]:
zeros_tensor = torch.zeros((5, 6)) # for ones as well

In [22]:
torch.rand(6)

tensor([0.0914, 0.6120, 0.6343, 0.7532, 0.7905, 0.9343])

In [23]:
torch.rand((4, 6))

tensor([[0.0979, 0.7402, 0.2232, 0.4109, 0.8403, 0.9009],
        [0.1808, 0.3867, 0.3371, 0.0513, 0.7556, 0.6949],
        [0.4462, 0.9483, 0.1042, 0.7896, 0.3867, 0.3052],
        [0.4522, 0.1181, 0.4525, 0.0826, 0.9709, 0.8861]])

In [24]:
x = torch.rand((4, 6))

In [25]:
x.shape

torch.Size([4, 6])

In [26]:
x.device # by default device is cpu

device(type='cpu')

In [29]:
# Operations on  tensor
tensor = torch.tensor([4,7,8])

In [33]:
tensor
# performs operations elementwise

tensor([4, 7, 8])

In [34]:
tensor + 5

tensor([ 9, 12, 13])

In [35]:
tensor*5

tensor([20, 35, 40])

In [36]:
tensor_2 = torch.tensor([1,2,3])

In [37]:
tensor_2

tensor([1, 2, 3])

In [38]:
tensor + tensor_2

tensor([ 5,  9, 11])

In [39]:
tensor*tensor_2

tensor([ 4, 14, 24])

In [41]:
x = torch.tensor([
    [1,2,3,4],
    [5,4,6,6],
    [1,5,3,7]
])

y = torch.tensor([
    [9,21,13,14],
    [1,7,4,2],
    [1,5,3,7]
])

In [42]:
x + y

tensor([[10, 23, 16, 18],
        [ 6, 11, 10,  8],
        [ 2, 10,  6, 14]])

In [48]:
x*y

tensor([[ 9, 42, 39, 56],
        [ 5, 28, 24, 12],
        [ 1, 25,  9, 49]])

In [49]:
%%time
x@y.T

CPU times: user 842 µs, sys: 0 ns, total: 842 µs
Wall time: 691 µs


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [50]:
%%time
torch.matmul(x, y.T) # faster

CPU times: user 136 µs, sys: 1.05 ms, total: 1.18 ms
Wall time: 1.19 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [51]:
%%time
torch.mm(x, y.T) # shorthand

CPU times: user 1.17 ms, sys: 0 ns, total: 1.17 ms
Wall time: 3.08 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [53]:
torch.arange(1, 10) # to generate an array

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
torch.arange(1, 100, 20)

tensor([ 1, 21, 41, 61, 81])

In [55]:
torch.linspace(1, 100, 20)

tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

In [57]:
torch.rand(1,10)

tensor([[0.8436, 0.0094, 0.6257, 0.8622, 0.6673, 0.8870, 0.2871, 0.8316, 0.7610,
         0.9423]])

In [63]:
torch.randint(1, 10, (3, 4))

tensor([[9, 4, 1, 3],
        [9, 8, 4, 8],
        [9, 5, 1, 9]])

In [69]:
x = torch.randint(1, 100, size = (20, ))

In [70]:
x

tensor([69, 47, 23, 54, 30,  3, 76, 81, 20, 26, 28, 59,  3, 58, 95, 95, 14, 70,
        58, 34])

In [71]:
x.min()

tensor(3)

In [72]:
x.max()

tensor(95)

In [73]:
x.sum()

tensor(943)

In [76]:
x.type(torch.float32).mean()

tensor(47.1500)

In [77]:
x = torch.randint(1, 50, size = (24, ))

In [78]:
x.shape

torch.Size([24])

In [80]:
x.reshape(4, 6)

tensor([[29, 47, 19, 45, 48, 33],
        [19, 29, 13, 32, 49, 25],
        [ 5, 49, 29, 35, 27, 27],
        [ 4, 31, 14, 16, 47, 24]])

In [81]:
x.reshape(2, 12)

tensor([[29, 47, 19, 45, 48, 33, 19, 29, 13, 32, 49, 25],
        [ 5, 49, 29, 35, 27, 27,  4, 31, 14, 16, 47, 24]])

In [82]:
x.view(6, 4)

tensor([[29, 47, 19, 45],
        [48, 33, 19, 29],
        [13, 32, 49, 25],
        [ 5, 49, 29, 35],
        [27, 27,  4, 31],
        [14, 16, 47, 24]])

In [83]:
x[0]

tensor(29)

In [84]:
x = x.reshape(4, 6)

In [85]:
x[0]

tensor([29, 47, 19, 45, 48, 33])

In [86]:
x[:0]

tensor([], size=(0, 6), dtype=torch.int64)

In [87]:
x[0:3, 0:2]

tensor([[29, 47],
        [19, 29],
        [ 5, 49]])