<a href="https://colab.research.google.com/github/Aashi779/DeepLearningwithPytorch/blob/main/SimpleANN_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

In [ ]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y

array([[1],
       [1],
       [0]])

**Activation Functions**

- Decide whether a neuron should be activated or not. Whether the information that the neuron is receiving is relevant for the given information or should it be ignored.
- It is the non linear transformation that we do over the input signal. This transformed output is then send to the next layer of neurons as input.
- Without activation function neural network will only be performing linear transformation on the input.
- A linear equation is simple to solve but is limited in its capacity to solve complex problems. A neural network without an activation function is essentially just a linear regression model.

In [ ]:
# Activation function
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
x.shape # gives a tuple

(3, 4)

In [ ]:
# input layer neurons will be always equals to the number of columns
inputNeurons = x.shape[1]
# hidden neurons we can decide by hit and trial
hiddenNeurons = 3
# output neurons depends on number of classes we have in target column,for eg to classify 0 and 1
outputNeurons = 1

In [ ]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons)) # (4,3)
biasHidden = np.random.uniform(size=(1, hiddenNeurons)) #(1,3)
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons)) #(3,1)
biasOutput = np.random.uniform(size=(1, outputNeurons)) #(1,1)

In [ ]:
# Feedforward

# Step 1 - apply dot product and add bias : f(x) = x.wh + biasHidden
fx = np.dot(x, weightsHidden) + biasHidden

# Step 2 - apply activation function
hiddenLayer = sigmoid(fx)
hiddenLayer

array([[0.70128954, 0.92769703, 0.87847941],
       [0.84379137, 0.93391848, 0.94265152],
       [0.77273892, 0.78806868, 0.84723194]])

In [ ]:
# Step-3 - apply dot product and add bias : f(x) = hiddenLayer.wout + biasOut
fx_ = np.dot(hiddenLayer, weightsOutput) + biasOutput
fx_


array([[2.49062423],
       [2.62208729],
       [2.41045676]])

Bias

In [ ]:
biasHidden

array([[0.24137394, 0.93698264, 0.79138208]])

In [ ]:
biasOutput

array([[0.91456034]])

In [ ]:
outputLayer = sigmoid(fx_) # applying activation on output layer

In [ ]:
outputLayer #predictions

array([[0.92348192],
       [0.93226962],
       [0.91762122]])

In [ ]:
def derivativeSigmoid(x):
  return x * (1 - x)

In [ ]:
# Backpropagation -
# calculate loss(y - y^) and optimization of weights and bias
# calc slope of activation function(derivative)
# delta - loss*slope

In [ ]:
# Error on output layer
errorOutput = outputLayer - y
# Slope on output layer - derivative of activation function applied on this layer
slopeOutput = derivativeSigmoid(outputLayer)
# Delta = error x slope
deltaOutput = errorOutput * slopeOutput

In [ ]:
# for hidden layer
errorHidden = np.dot(deltaOutput, weightsOutput.T)
slopeHidden = derivativeSigmoid(hiddenLayer)
deltaHidden = errorHidden * slopeHidden

In [ ]:
errorOutput # this has to be minimized

array([[-0.07651808],
       [-0.06773038],
       [ 0.91762122]])

In [ ]:
# updating the weights (weights optimization)
alpha = 0.01
weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput)*alpha
weightsHidden = weightsHidden - x.T.dot(deltaHidden)*alpha
biasOutput = biasOutput - np.sum(deltaOutput)*alpha
biasHidden = biasHidden - np.sum(deltaOutput)*alpha

In [ ]:
weightsHidden = np.random.uniform(size=(inputNeurons, hiddenNeurons)) # (4,3)
biasHidden = np.random.uniform(size=(1, hiddenNeurons)) #(1,3)
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons)) #(3,1)
biasOutput = np.random.uniform(size=(1, outputNeurons)) #(1,1)

In [ ]:
# need to run the code in a loop and run it until we get an optimized result(combined)

alpha = 0.04
epochs = 20000

for i in range(epochs):
  # Step 1 - apply dot product and add bias : f(x) = x.wh + biasHidden
  fx = np.dot(x, weightsHidden) + biasHidden

  # Step 2 - apply activation function
  hiddenLayer = sigmoid(fx)

  # Step-3 - apply dot product and add bias : f(x) = hiddenLayer.wout + biasOut
  fx_ = np.dot(hiddenLayer, weightsOutput) + biasOutput

  # Step 4 - appy activation on output layer
  outputLayer = sigmoid(fx_)

  errorOutput = outputLayer - y
  # Slope on output layer - derivative of activation function applied on this layer
  slopeOutput = derivativeSigmoid(outputLayer)
  # Delta = error x slope
  deltaOutput = errorOutput * slopeOutput

  # for hidden layer
  errorHidden = np.dot(deltaOutput, weightsOutput.T)
  slopeHidden = derivativeSigmoid(hiddenLayer)
  deltaHidden = errorHidden * slopeHidden


  weightsOutput = weightsOutput - hiddenLayer.T.dot(deltaOutput)*alpha
  weightsHidden = weightsHidden - x.T.dot(deltaHidden)*alpha
  biasOutput = biasOutput - np.sum(deltaOutput)*alpha
  biasHidden = biasHidden - np.sum(deltaOutput)*alpha

In [ ]:
outputLayer

array([[0.98788798],
       [0.98006967],
       [0.02688157]])

NameError: ignored